#!/usr/bin/env python3
"""Generate pc/include/pc_shader_seed.h from a shader_cache.bin.

The seed embeds known shader-config keys in the binary so a fresh install
precompiles them at boot instead of hitching on first encounter mid-game.
Regenerate after a thorough play session (the game appends newly seen keys
to shader_cache.bin next to the exe):

    python pc/tools/gen_shader_seed.py pc/build32/bin/shader_cache.bin

The runtime cache only records keys NOT already covered by the built-in
seed, so this tool merges: existing pc_shader_seed.h keys + new cache keys.
Existing seed keys with a different key size are dropped (stale format).
"""
import re
import struct
import sys
import os

MAGIC = 0x41435356  # ACSV


def read_existing_seed(path, key_size):
    """Return keys from a previously generated header, [] if absent/stale."""
    try:
        text = open(path).read()
    except OSError:
        return []
    m = re.search(r"#define PC_SHADER_SEED_KEY_SIZE (\d+)", text)
    if not m or int(m.group(1)) != key_size:
        if m:
            print("note: existing seed key size %s != %d, dropping old keys"
                  % (m.group(1), key_size))
        return []
    keys = []
    for row in re.findall(r"^    \{([\d,]+)\},$", text, re.M):
        keys.append(bytes(int(b) for b in row.split(",")))
    return keys


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 1

    cache_path = sys.argv[1]
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "..", "include", "pc_shader_seed.h")

    data = open(cache_path, "rb").read()
    magic, key_size = struct.unpack("<II", data[:8])
    if magic != MAGIC:
        print("error: bad magic in %s" % cache_path)
        return 1

    keys = []
    seen = set()
    old = read_existing_seed(out_path, key_size)
    body = data[8:]
    new_keys = [body[i * key_size:(i + 1) * key_size]
                for i in range(len(body) // key_size)]
    for k in old + new_keys:
        if k not in seen:
            seen.add(k)
            keys.append(k)
    print("merged: %d existing + %d from cache -> %d unique"
          % (len(old), len(new_keys), len(keys)))

    with open(out_path, "w", newline="\n") as f:
        f.write("/* Auto-generated by pc/tools/gen_shader_seed.py - do not edit.\n")
        f.write(" * Shader config keys precompiled at boot (see pc_gx_tev.c). */\n")
        f.write("#ifndef PC_SHADER_SEED_H\n#define PC_SHADER_SEED_H\n\n")
        f.write("#define PC_SHADER_SEED_KEY_SIZE %d\n" % key_size)
        f.write("#define PC_SHADER_SEED_COUNT %d\n\n" % len(keys))
        f.write("static const unsigned char pc_shader_seed_keys"
                "[PC_SHADER_SEED_COUNT][PC_SHADER_SEED_KEY_SIZE] = {\n")
        for k in keys:
            f.write("    {" + ",".join(str(b) for b in k) + "},\n")
        f.write("};\n\n#endif /* PC_SHADER_SEED_H */\n")

    print("wrote %s: %d keys (key size %d)" % (out_path, len(keys), key_size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
