/* pc_save_legacy_layout.h - GENERATED by gen_legacy_layout.py from the
 * four-resident headers (PLAYER_NUM 4). Offsets and sizes of every field
 * of the old Save_t and its nested structs, for pc_save_convert.c. Do not
 * edit by hand. */
#ifndef PC_SAVE_LEGACY_LAYOUT_H
#define PC_SAVE_LEGACY_LAYOUT_H

#define LEGACY_PLAYER_NUM 4
#define LEGACY_SIZEOF_Save_t 148128
#define LEGACY_SIZEOF_Save 155648
#define LEGACY_SIZEOF_Private_c 9280
#define LEGACY_SIZEOF_mHm_hs_c 9904
#define LEGACY_SIZEOF_Animal_c 2440
#define LEGACY_SIZEOF_Island_c 6400
#define LEGACY_SIZEOF_mCD_keep_diary_c 47618
#define LEGACY_SIZEOF_mCD_keep_original_c 52384
#define LEGACY_SIZEOF_mCD_keep_mail_c 47780
#define LEGACY_SIZEOF_MemcardHeader_c 5184
#define LEGACY_SIZEOF_mEv_event_save_c 188
#define LEGACY_SIZEOF_mEv_weekly_u 100
#define LEGACY_SIZEOF_mAGrw_SSPosInfo_c 4
#define LEGACY_SIZEOF_AnmHPMail_c 28
#define LEGACY_SIZEOF_mPr_mother_mail_info_c 14
#define LEGACY_SIZEOF_PersonalID_c 20
#define LEGACY_SIZEOF_mDi_entry_c 992
#define LEGACY_SIZEOF_Save_t 148128
#define LEGACY_OTHERS_SIZE 155648
#define LEGACY_mCD_LAND_SAVE_SIZE 466944

/* Save_t fields, in declaration order: offset and size. */
#define LEGACY_OFF_save_check 0
#define LEGACY_SIZE_save_check 20
#define LEGACY_OFF_scene_no 20
#define LEGACY_SIZE_scene_no 4
#define LEGACY_OFF_now_npc_max 24
#define LEGACY_SIZE_now_npc_max 1
#define LEGACY_OFF_remove_animal_idx 25
#define LEGACY_SIZE_remove_animal_idx 1
#define LEGACY_OFF_copy_protect 26
#define LEGACY_SIZE_copy_protect 2
#define LEGACY_OFF_pad_1C 28
#define LEGACY_SIZE_pad_1C 4
#define LEGACY_OFF_private_data 32
#define LEGACY_SIZE_private_data 37120
#define LEGACY_OFF_land_info 37152
#define LEGACY_SIZE_land_info 12
#define LEGACY_OFF_noticeboard 37164
#define LEGACY_SIZE_noticeboard 3000
#define LEGACY_OFF_pad_9CE4 40164
#define LEGACY_SIZE_pad_9CE4 4
#define LEGACY_OFF_homes 40168
#define LEGACY_SIZE_homes 39616
#define LEGACY_OFF_fg 79784
#define LEGACY_SIZE_fg 15360
#define LEGACY_OFF_combi_table 95144
#define LEGACY_SIZE_combi_table 140
#define LEGACY_OFF_animals 95288
#define LEGACY_SIZE_animals 36600
#define LEGACY_OFF_last_removed_animal_id 131888
#define LEGACY_SIZE_last_removed_animal_id 14
#define LEGACY_OFF_shop 131904
#define LEGACY_SIZE_shop 320
#define LEGACY_OFF_kabu_price_schedule 132224
#define LEGACY_SIZE_kabu_price_schedule 24
#define LEGACY_OFF_event_save_data 132248
#define LEGACY_SIZE_event_save_data 188
#define LEGACY_OFF_event_save_common 132436
#define LEGACY_SIZE_event_save_common 308
#define LEGACY_OFF_fruit 132744
#define LEGACY_SIZE_fruit 2
#define LEGACY_OFF_house_arrangement 132746
#define LEGACY_SIZE_house_arrangement 1
#define LEGACY_OFF_num_statues 132747
#define LEGACY_SIZE_num_statues 1
#define LEGACY_OFF_all_grow_renew_time 132748
#define LEGACY_SIZE_all_grow_renew_time 8
#define LEGACY_OFF_post_office 132756
#define LEGACY_SIZE_post_office 2108
#define LEGACY_OFF_police_box 134864
#define LEGACY_SIZE_police_box 40
#define LEGACY_OFF_snowmen 134904
#define LEGACY_SIZE_snowmen 12
#define LEGACY_OFF_melody 134920
#define LEGACY_SIZE_melody 8
#define LEGACY_OFF_config 134928
#define LEGACY_SIZE_config 4
#define LEGACY_OFF_renew_time 134932
#define LEGACY_SIZE_renew_time 4
#define LEGACY_OFF_station_type 134936
#define LEGACY_SIZE_station_type 1
#define LEGACY_OFF_weather 134937
#define LEGACY_SIZE_weather 1
#define LEGACY_OFF_save_exist 134938
#define LEGACY_SIZE_save_exist 1
#define LEGACY_OFF_npc_force_go_home 134939
#define LEGACY_SIZE_npc_force_go_home 1
#define LEGACY_OFF_deposit 134940
#define LEGACY_SIZE_deposit 960
#define LEGACY_OFF_last_grow_time 135900
#define LEGACY_SIZE_last_grow_time 8
#define LEGACY_OFF_mother_mail 135908
#define LEGACY_SIZE_mother_mail 56
#define LEGACY_OFF_mushroom_time 135964
#define LEGACY_SIZE_mushroom_time 6
#define LEGACY_OFF__021322 135970
#define LEGACY_SIZE__021322 4
#define LEGACY_OFF__021326 135974
#define LEGACY_SIZE__021326 40
#define LEGACY_OFF_npc_used_tbl 136014
#define LEGACY_SIZE_npc_used_tbl 32
#define LEGACY_OFF__02136E 136046
#define LEGACY_SIZE__02136E 8
#define LEGACY_OFF_cheated_flag 136054
#define LEGACY_SIZE_cheated_flag 1
#define LEGACY_OFF__021377 136055
#define LEGACY_SIZE__021377 7
#define LEGACY_OFF_treasure_buried_time 136062
#define LEGACY_SIZE_treasure_buried_time 8
#define LEGACY_OFF_treasure_checked_time 136070
#define LEGACY_SIZE_treasure_checked_time 8
#define LEGACY_OFF_saved_rom_debug 136078
#define LEGACY_SIZE_saved_rom_debug 1
#define LEGACY_OFF_snowman_year 136079
#define LEGACY_SIZE_snowman_year 1
#define LEGACY_OFF_snowman_month 136080
#define LEGACY_SIZE_snowman_month 1
#define LEGACY_OFF_snowman_day 136081
#define LEGACY_SIZE_snowman_day 1
#define LEGACY_OFF_snowman_hour 136082
#define LEGACY_SIZE_snowman_hour 1
#define LEGACY_OFF_haniwa_scheduled 136083
#define LEGACY_SIZE_haniwa_scheduled 1
#define LEGACY_OFF_dust_flag 136084
#define LEGACY_SIZE_dust_flag 1
#define LEGACY_OFF_clear_grass 136085
#define LEGACY_SIZE_clear_grass 1
#define LEGACY_OFF__021396 136086
#define LEGACY_SIZE__021396 2
#define LEGACY_OFF_event_year 136088
#define LEGACY_SIZE_event_year 2
#define LEGACY_OFF_unused_2139C 136090
#define LEGACY_SIZE_unused_2139C 6
#define LEGACY_OFF_keep_house_size 136096
#define LEGACY_SIZE_keep_house_size 4
#define LEGACY_OFF_force_remove_date 136100
#define LEGACY_SIZE_force_remove_date 4
#define LEGACY_OFF_museum_display 136104
#define LEGACY_SIZE_museum_display 63
#define LEGACY_OFF__tmp6 136167
#define LEGACY_SIZE__tmp6 9
#define LEGACY_OFF_bridge 136176
#define LEGACY_SIZE_bridge 8
#define LEGACY_OFF_needlework 136192
#define LEGACY_SIZE_needlework 4352
#define LEGACY_OFF__tmp7 140544
#define LEGACY_SIZE__tmp7 40
#define LEGACY_OFF_time_delta 140584
#define LEGACY_SIZE_time_delta 8
#define LEGACY_OFF_island 140608
#define LEGACY_SIZE_island 6400
#define LEGACY_OFF_allgrow_ss_pos_info 147008
#define LEGACY_SIZE_allgrow_ss_pos_info 40
#define LEGACY_OFF_fishRecord 147048
#define LEGACY_SIZE_fishRecord 160
#define LEGACY_OFF_mask_cat 147232
#define LEGACY_SIZE_mask_cat 576
#define LEGACY_OFF_return_animal 147808
#define LEGACY_SIZE_return_animal 12
#define LEGACY_OFF_LightHouse 147820
#define LEGACY_SIZE_LightHouse 8
#define LEGACY_OFF_insect_term 147828
#define LEGACY_SIZE_insect_term 1
#define LEGACY_OFF_insect_term_transition_offset 147829
#define LEGACY_SIZE_insect_term_transition_offset 1
#define LEGACY_OFF_gyoei_term 147830
#define LEGACY_SIZE_gyoei_term 1
#define LEGACY_OFF_gyoei_term_transition_offset 147831
#define LEGACY_SIZE_gyoei_term_transition_offset 1
#define LEGACY_OFF_good_field 147832
#define LEGACY_SIZE_good_field 12
#define LEGACY_OFF_bg_tex_idx 147844
#define LEGACY_SIZE_bg_tex_idx 1
#define LEGACY_OFF_rainbow_month 147845
#define LEGACY_SIZE_rainbow_month 1
#define LEGACY_OFF_rainbow_day 147846
#define LEGACY_SIZE_rainbow_day 1
#define LEGACY_OFF_rainbow_reserved 147847
#define LEGACY_SIZE_rainbow_reserved 1
#define LEGACY_OFF__24188 147848
#define LEGACY_SIZE__24188 1
#define LEGACY_OFF_first_present 147849
#define LEGACY_SIZE_first_present 1
#define LEGACY_OFF_town_day 147850
#define LEGACY_SIZE_town_day 1
#define LEGACY_OFF__2418B 147851
#define LEGACY_SIZE__2418B 13
#define LEGACY_OFF_travel_hard_time 147864
#define LEGACY_SIZE_travel_hard_time 8
#define LEGACY_OFF_saved_auto_nwrite_time 147872
#define LEGACY_SIZE_saved_auto_nwrite_time 8
#define LEGACY_OFF__241A8 147880
#define LEGACY_SIZE__241A8 248

/* The field names of Save_t, in order, for the converter's copy loop. */
#define LEGACY_SAVE_FIELDS(X) \
    X(save_check) \
    X(scene_no) \
    X(now_npc_max) \
    X(remove_animal_idx) \
    X(copy_protect) \
    X(pad_1C) \
    X(private_data) \
    X(land_info) \
    X(noticeboard) \
    X(pad_9CE4) \
    X(homes) \
    X(fg) \
    X(combi_table) \
    X(animals) \
    X(last_removed_animal_id) \
    X(shop) \
    X(kabu_price_schedule) \
    X(event_save_data) \
    X(event_save_common) \
    X(fruit) \
    X(house_arrangement) \
    X(num_statues) \
    X(all_grow_renew_time) \
    X(post_office) \
    X(police_box) \
    X(snowmen) \
    X(melody) \
    X(config) \
    X(renew_time) \
    X(station_type) \
    X(weather) \
    X(save_exist) \
    X(npc_force_go_home) \
    X(deposit) \
    X(last_grow_time) \
    X(mother_mail) \
    X(mushroom_time) \
    X(_021322) \
    X(_021326) \
    X(npc_used_tbl) \
    X(_02136E) \
    X(cheated_flag) \
    X(_021377) \
    X(treasure_buried_time) \
    X(treasure_checked_time) \
    X(saved_rom_debug) \
    X(snowman_year) \
    X(snowman_month) \
    X(snowman_day) \
    X(snowman_hour) \
    X(haniwa_scheduled) \
    X(dust_flag) \
    X(clear_grass) \
    X(_021396) \
    X(event_year) \
    X(unused_2139C) \
    X(keep_house_size) \
    X(force_remove_date) \
    X(museum_display) \
    X(_tmp6) \
    X(bridge) \
    X(needlework) \
    X(_tmp7) \
    X(time_delta) \
    X(island) \
    X(allgrow_ss_pos_info) \
    X(fishRecord) \
    X(mask_cat) \
    X(return_animal) \
    X(LightHouse) \
    X(insect_term) \
    X(insect_term_transition_offset) \
    X(gyoei_term) \
    X(gyoei_term_transition_offset) \
    X(good_field) \
    X(bg_tex_idx) \
    X(rainbow_month) \
    X(rainbow_day) \
    X(rainbow_reserved) \
    X(_24188) \
    X(first_present) \
    X(town_day) \
    X(_2418B) \
    X(travel_hard_time) \
    X(saved_auto_nwrite_time) \
    X(_241A8) \
    /* end */

/* The fields whose bytes copy across unchanged (same size and meaning in
 * both layouts); the rest are converted by hand in pc_save_convert.c. */
#define LEGACY_SAVE_PLAIN_FIELDS(X) \
    X(save_check) \
    X(scene_no) \
    X(now_npc_max) \
    X(remove_animal_idx) \
    X(copy_protect) \
    X(pad_1C) \
    X(land_info) \
    X(noticeboard) \
    X(pad_9CE4) \
    X(combi_table) \
    X(last_removed_animal_id) \
    X(shop) \
    X(kabu_price_schedule) \
    X(event_save_common) \
    X(fruit) \
    X(num_statues) \
    X(all_grow_renew_time) \
    X(post_office) \
    X(police_box) \
    X(snowmen) \
    X(melody) \
    X(config) \
    X(renew_time) \
    X(station_type) \
    X(weather) \
    X(save_exist) \
    X(npc_force_go_home) \
    X(deposit) \
    X(last_grow_time) \
    X(mushroom_time) \
    X(_021322) \
    X(_021326) \
    X(npc_used_tbl) \
    X(_02136E) \
    X(cheated_flag) \
    X(_021377) \
    X(treasure_buried_time) \
    X(treasure_checked_time) \
    X(saved_rom_debug) \
    X(snowman_year) \
    X(snowman_month) \
    X(snowman_day) \
    X(snowman_hour) \
    X(haniwa_scheduled) \
    X(dust_flag) \
    X(clear_grass) \
    X(_021396) \
    X(event_year) \
    X(unused_2139C) \
    X(force_remove_date) \
    X(_tmp6) \
    X(bridge) \
    X(needlework) \
    X(_tmp7) \
    X(time_delta) \
    X(fishRecord) \
    X(mask_cat) \
    X(return_animal) \
    X(insect_term) \
    X(insect_term_transition_offset) \
    X(gyoei_term) \
    X(gyoei_term_transition_offset) \
    X(good_field) \
    X(bg_tex_idx) \
    X(rainbow_month) \
    X(rainbow_day) \
    X(rainbow_reserved) \
    X(_24188) \
    X(first_present) \
    X(town_day) \
    X(_2418B) \
    X(travel_hard_time) \
    X(saved_auto_nwrite_time) \
    /* end */

/* Nested structs. */
#define LEGACY_ANIMAL_OFF_id 0
#define LEGACY_ANIMAL_SIZE_id 14
#define LEGACY_ANIMAL_OFF_memories 16
#define LEGACY_ANIMAL_SIZE_memories 2184
#define LEGACY_ANIMAL_OFF_home_info 2200
#define LEGACY_ANIMAL_SIZE_home_info 5
#define LEGACY_ANIMAL_OFF_catchphrase 2205
#define LEGACY_ANIMAL_SIZE_catchphrase 10
#define LEGACY_ANIMAL_OFF_contest_quest 2216
#define LEGACY_ANIMAL_SIZE_contest_quest 40
#define LEGACY_ANIMAL_OFF_parent_name 2256
#define LEGACY_ANIMAL_SIZE_parent_name 8
#define LEGACY_ANIMAL_OFF_anmuni 2264
#define LEGACY_ANIMAL_SIZE_anmuni 8
#define LEGACY_ANIMAL_OFF_previous_land_id 2272
#define LEGACY_ANIMAL_SIZE_previous_land_id 2
#define LEGACY_ANIMAL_OFF_mood 2274
#define LEGACY_ANIMAL_SIZE_mood 1
#define LEGACY_ANIMAL_OFF_mood_time 2275
#define LEGACY_ANIMAL_SIZE_mood_time 1
#define LEGACY_ANIMAL_OFF_cloth 2276
#define LEGACY_ANIMAL_SIZE_cloth 2
#define LEGACY_ANIMAL_OFF_remove_info 2278
#define LEGACY_ANIMAL_SIZE_remove_info 2
#define LEGACY_ANIMAL_OFF_is_home 2280
#define LEGACY_ANIMAL_SIZE_is_home 1
#define LEGACY_ANIMAL_OFF_moved_in 2281
#define LEGACY_ANIMAL_SIZE_moved_in 1
#define LEGACY_ANIMAL_OFF_removing 2282
#define LEGACY_ANIMAL_SIZE_removing 1
#define LEGACY_ANIMAL_OFF_cloth_original_id 2283
#define LEGACY_ANIMAL_SIZE_cloth_original_id 1
#define LEGACY_ANIMAL_OFF_umbrella_id 2284
#define LEGACY_ANIMAL_SIZE_umbrella_id 1
#define LEGACY_ANIMAL_OFF_unk_8ED 2285
#define LEGACY_ANIMAL_SIZE_unk_8ED 1
#define LEGACY_ANIMAL_OFF_present_cloth 2286
#define LEGACY_ANIMAL_SIZE_present_cloth 2
#define LEGACY_ANIMAL_OFF_animal_relations 2288
#define LEGACY_ANIMAL_SIZE_animal_relations 15
#define LEGACY_ANIMAL_OFF_hp_mail 2304
#define LEGACY_ANIMAL_SIZE_hp_mail 112
#define LEGACY_ANIMAL_OFF_unused 2416
#define LEGACY_ANIMAL_SIZE_unused 24
#define LEGACY_ISLAND_OFF_name 0
#define LEGACY_ISLAND_SIZE_name 8
#define LEGACY_ISLAND_OFF_landinfo 8
#define LEGACY_ISLAND_SIZE_landinfo 12
#define LEGACY_ISLAND_OFF_fgblock 20
#define LEGACY_ISLAND_SIZE_fgblock 1024
#define LEGACY_ISLAND_OFF_cottage 1048
#define LEGACY_ISLAND_SIZE_cottage 2248
#define LEGACY_ISLAND_OFF_flag_design 3296
#define LEGACY_ISLAND_SIZE_flag_design 544
#define LEGACY_ISLAND_OFF_animal 3840
#define LEGACY_ISLAND_SIZE_animal 2440
#define LEGACY_ISLAND_OFF_deposit 6280
#define LEGACY_ISLAND_SIZE_deposit 64
#define LEGACY_ISLAND_OFF_bg_data 6344
#define LEGACY_ISLAND_SIZE_bg_data 2
#define LEGACY_ISLAND_OFF_renew_time 6346
#define LEGACY_ISLAND_SIZE_renew_time 8
#define LEGACY_ISLAND_OFF_unused_18D2 6354
#define LEGACY_ISLAND_SIZE_unused_18D2 14
#define LEGACY_ISLAND_OFF_grass_tex_type 6368
#define LEGACY_ISLAND_SIZE_grass_tex_type 1
#define LEGACY_ISLAND_OFF_last_song_to_island 6369
#define LEGACY_ISLAND_SIZE_last_song_to_island 1
#define LEGACY_ISLAND_OFF_last_song_from_island 6370
#define LEGACY_ISLAND_SIZE_last_song_from_island 1
#define LEGACY_ISLAND_OFF_unused_18E3 6371
#define LEGACY_ISLAND_SIZE_unused_18E3 29
#define LEGACY_EVSAVE_OFF_special 0
#define LEGACY_EVSAVE_SIZE_special 84
#define LEGACY_EVSAVE_OFF_weekly 84
#define LEGACY_EVSAVE_SIZE_weekly 100
#define LEGACY_EVSAVE_OFF_flags 184
#define LEGACY_EVSAVE_SIZE_flags 4
#define LEGACY_ALLGROW_OFF_shine_pos 0
#define LEGACY_ALLGROW_SIZE_shine_pos 20
#define LEGACY_ALLGROW_OFF_stone_pos 20
#define LEGACY_ALLGROW_SIZE_stone_pos 20
#define LEGACY_LIGHTHOUSE_OFF_renew_time 0
#define LEGACY_LIGHTHOUSE_SIZE_renew_time 4
#define LEGACY_LIGHTHOUSE_OFF_days_switched_on 4
#define LEGACY_LIGHTHOUSE_SIZE_days_switched_on 1
#define LEGACY_LIGHTHOUSE_OFF_players_quest_started 5
#define LEGACY_LIGHTHOUSE_SIZE_players_quest_started 1
#define LEGACY_LIGHTHOUSE_OFF_players_completed 6
#define LEGACY_LIGHTHOUSE_SIZE_players_completed 1
#define LEGACY_OTHERS_OFF_header 0
#define LEGACY_OTHERS_SIZE_header 5184
#define LEGACY_OTHERS_OFF_pad 5184
#define LEGACY_OTHERS_SIZE_pad 32
#define LEGACY_OTHERS_OFF_original 5216
#define LEGACY_OTHERS_SIZE_original 52384
#define LEGACY_OTHERS_OFF_mail 57600
#define LEGACY_OTHERS_SIZE_mail 47780
#define LEGACY_OTHERS_OFF_diary 105408
#define LEGACY_OTHERS_SIZE_diary 47618

#endif /* PC_SAVE_LEGACY_LAYOUT_H */
