#include "jaudio_NES/audiowork.h"

AudioGlobals AG;
VFRAME_CALLBACK NA_VFRAME_CALLBACK;
SequenceCallback NA_CALLBACK;
GRP_CALLBACK NA_GRP_CALLBACK;
SOUND_CALLBACK NA_SOUND_CALLBACK;
DACOUT_CALLBACK NA_DACOUT_CALLBACK;
